image: node:lts

cache: &default_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

variables:
  CI: "true"

stages:
  - install_dependencies
  - lint
  # - test
  - test_e2e
  - build
  # - release

install_dependencies:
  tags:
    - docker-executor
  stage: install_dependencies
  cache:
    <<: *default_cache
    policy: pull-push
  script:
    - npm ci

lint:
  tags:
    - docker-executor
  stage: lint
  script:
    - npm run lint

.test:
  tags:
    - docker-executor
  stage: test
  script:
    - npm run test

test_e2e:
  stage: test_e2e
  image: samujoha/gitlab-ci-puppeteer-headful:latest
  tags:
    - docker-executor
  before_script:
    - chmod -R +x ./ci
  script:
    - ./ci/setup-e2e-env.sh
    - npm run test:e2e
  artifacts:
    when: on_failure
    paths:
      - ./e2e/__image_snapshots__/__diff_output__
    expire_in: 30 days

test_e2e_update:
  stage: test_e2e
  image: samujoha/gitlab-ci-puppeteer-headful:latest
  tags:
    - docker-executor
  before_script:
    - chmod -R +x ./ci
  script:
    - ./ci/setup-e2e-env.sh
    - npm run test:e2e-update
    - './ci/gitlab-commit-push.sh "test(e2e): update baseline snapshots [skip ci]"'
  when: manual

build:
  tags:
    - docker-executor
  stage: build
  script:
    - npm run build
  # artifacts:
  #   paths:
  #     - ./build
  #   expire_in: 1 day

.release:
  tags:
    - docker-executor
  stage: release
  script:
    - npx semantic-release --branch master
  only:
    - master
