image: node:lts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  CI: "true"

stages:
  - install_dependencies
  - lint
  - test
  - build
  # - release

install_dependencies:
  stage: install_dependencies
  tags:
    - docker-executor
  script:
    - npm ci

lint:
  tags:
    - docker-executor
  stage: lint
  script:
    - npm run lint

test:
  tags:
    - docker-executor
  stage: test
  script:
    - npm run test

build:
  tags:
    - docker-executor
  stage: build
  artifacts:
    paths:
      - ./build
    expire_in: 1 day
  script:
    - npm run build
# release:
#   tags:
#     - docker-executor
#   stage: release
#   script:
#     - npx semantic-release --branch master
#   only:
#     - master
