image: node:12.16.3

cache: &default_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

variables:
  CI: "true"

stages:
  - install_dependencies
  - lint
  - test
  - build
  - release
  - deploy

install_dependencies:
  tags:
    - linux-docker
  stage: install_dependencies
  cache:
    <<: *default_cache
    policy: pull-push
  script:
    - npm ci

lint:
  tags:
    - linux-docker
  stage: lint
  script:
    - npm run lint

test:
  tags:
    - linux-docker
  stage: test
  script:
    - npm run test

test_e2e:
  tags:
    - windows
  stage: test
  before_script:
    - npm ci
  script:
    - npm run test:e2e
    - './ci/gitlab-commit-push.ps1 "test(e2e): update baseline snapshots [skip ci]"'
  artifacts:
    when: on_failure
    paths:
      - ./e2e/__image_snapshots__/__diff_output__
    expire_in: 30 days

test_e2e_update:
  tags:
    - windows
  stage: test
  when: manual
  before_script:
    - npm ci
  script:
    - npm run test:e2e-update
    - './ci/gitlab-commit-push.ps1 "test(e2e): update baseline snapshots [skip ci]"'

build:
  tags:
    - linux-docker
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - $BUILD_FOLDER
    expire_in: 1 week

.release:
  tags:
    - linux-docker
  stage: release
  script:
    - npx semantic-release
  only:
    - master

deploy:
  tags:
    - linux-docker
  stage: deploy
  only:
    - master
  dependencies:
    - build
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
  script:
    - lftp -e "open $FTP_HOSTNAME; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete $BUILD_FOLDER/ $FTP_DEST_FOLDER/; bye"
