packageExtensions:
  eslint-module-utils@*:
    peerDependencies:
      eslint-import-resolver-node: latest
  eslint-config-react-app@*:
    peerDependencies:
      eslint-plugin-flowtype: latest

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-sources.js
